//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealAnggaran.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RealAnggaran.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap browse_icon {
            get {
                object obj = ResourceManager.GetObject("browse_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infomasi.
        /// </summary>
        internal static string CAlat_PengecekField_Infomasi {
            get {
                return ResourceManager.GetString("CAlat_PengecekField_Infomasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipe data tidak di kenali.
        /// </summary>
        internal static string CAlat_PengecekField_Tipe_data_tidak_di_kenali {
            get {
                return ResourceManager.GetString("CAlat_PengecekField_Tipe_data_tidak_di_kenali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terjadi kesalahan penulisan excel
        ///Pesan kesalahan : .
        /// </summary>
        internal static string FCetakTransaksi_backgroundWorker2_DoWork_ {
            get {
                return ResourceManager.GetString("FCetakTransaksi_backgroundWorker2_DoWork_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File GAGAL Tercetak.
        /// </summary>
        internal static string FCetakTransaksi_backgroundWorker2_DoWork_File_GAGAL_Tercetak {
            get {
                return ResourceManager.GetString("FCetakTransaksi_backgroundWorker2_DoWork_File_GAGAL_Tercetak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Exported.
        /// </summary>
        internal static string FCetakTransaksi_backgroundWorker2_DoWork_File_Tercetak {
            get {
                return ResourceManager.GetString("FCetakTransaksi_backgroundWorker2_DoWork_File_Tercetak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KONFIRMASI.
        /// </summary>
        internal static string FCetakTransaksi_backgroundWorker2_DoWork_KONFIRMASI {
            get {
                return ResourceManager.GetString("FCetakTransaksi_backgroundWorker2_DoWork_KONFIRMASI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Excel tidak ditemukan!
        ///Silahkan klik template dan arahkan ke file template tersebut
        ///Lebih lanjut hubungi 1062.
        /// </summary>
        internal static string FCetakTransaksi_button1_Click_ {
            get {
                return ResourceManager.GetString("FCetakTransaksi_button1_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERHATIAN.
        /// </summary>
        internal static string FCetakTransaksi_button1_Click_PERHATIAN {
            get {
                return ResourceManager.GetString("FCetakTransaksi_button1_Click_PERHATIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silahkan Pilih Jenis Tanggal
        ///SPK atau SPJ.
        /// </summary>
        internal static string FCetakTransaksi_button1_Click_pilih {
            get {
                return ResourceManager.GetString("FCetakTransaksi_button1_Click_pilih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silahkan pilih file yg akan dieksekusi!.
        /// </summary>
        internal static string FCetakTransaksi_button1_Click_Silahkan_pilih_file_yg_akan_dieksekusi_ {
            get {
                return ResourceManager.GetString("FCetakTransaksi_button1_Click_Silahkan_pilih_file_yg_akan_dieksekusi_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masih Ada Proses berjalan harap tunggu.
        /// </summary>
        internal static string FCetakTransaksi_fCetakTransaksi_FormClosing_Masih_Ada_Proses_berjalan_harap_tunggu {
            get {
                return ResourceManager.GetString("FCetakTransaksi_fCetakTransaksi_FormClosing_Masih_Ada_Proses_berjalan_harap_tungg" +
                        "u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Occured while releasing object .
        /// </summary>
        internal static string FCetakTransaksi_releaseObject_Exception_Occured_while_releasing_object_ {
            get {
                return ResourceManager.GetString("FCetakTransaksi_releaseObject_Exception_Occured_while_releasing_object_", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Folder___Factory_Bank {
            get {
                object obj = ResourceManager.GetObject("Folder - Factory Bank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap print_printer {
            get {
                object obj = ResourceManager.GetObject("print_printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ttfIcon {
            get {
                object obj = ResourceManager.GetObject("ttfIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tutor {
            get {
                object obj = ResourceManager.GetObject("tutor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
